Br54 test module for batch
mlgym/mlgym pull request #66
Opened 2022-05-29 23:03 UTC by zengxyu

2022-06-01 09:59 UTC, le1nux requested changes
Thanks for the PR. I left a couple of remarks which we need to address before merging it :-)

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        requirements = {"iterators": Requirement(components=informed_iterators, subscription=["train", "test"])}
Collator does not have a dependency for iterators. A dataloader does.

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +class TestDataCollatorConstructable(IteratorFixtures):
this is not a higher level iterator constructable. I think we should move this.

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +class TestDataLoadersConstructable(IteratorFixtures):
this is not a higher level iterator constructable. I think we should move this.

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +class TestOptimizerConstructable:
this is not a higher level iterator constructable. I think we should move this.

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +class TestOptimizerConstructable:
same goes for all the constructables below

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +    def test_constructable(self, informed_iterators):
Ok, so now we test if the component can be **constructed**. I think in a second step we should also test the **functionality** of the constructed component as well. In the case of the inmemory dataset iterator, we would check if everything is loaded into memory correctly, for instance. We should discuss this. :)

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        assert (shuffled_sample != sample).any()
Even if we shuffle, couldn't it also be the that just by chance the two match?

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        assert (shuffled_sample != sample).any()
(even if unlikely)

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +# class TestOneHotEncodedTargetsIteratorConstructable(IteratorFixtures):
can this be removed?

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        iterators = constructable.construct()
iterators name is misleading

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        requirements = {"iterators": Requirement(components=informed_iterators, subscription=["train", "test"])}
collator does not have this requirement

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        sampling_strategies = {'train': {"strategy": "RANDOM", "seed": 0},
we also have IN_ORDER now, could you add that as well please?

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        assert iterators._optimizer_class == SGD
Not an iterator. Same hold for the variables below

2022-06-01 09:59 UTC, le1nux commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        assert iterators[
I guess these checks are a bit redundant. They don't test functionality but rather "static assignments"

2022-06-01 10:07 UTC, zengxyu commented on pytest/blueprints/constructables/test_higher_order_iterator_constructables.py
> +        return MNISTCollator
you are right, I will rename it

2022-06-15 14:16 UTC, le1nux requested changes
I think we are almost there. Just a few tweaks here and there and we can merge :-)

2022-06-22 12:22 UTC, le1nux approved these changes
Looks good to me! Good work! :-)

2022-06-22 12:22 UTC, merged