Br72 test module loss function
mlgym/mlgym pull request #73
Opened 2022-06-21 20:40 UTC by zengxyu

2022-06-24 09:04 UTC, le1nux requested changes
Left a few comments. I think we can merge this soon :)

2022-07-05 22:17 UTC, zengxyu commented on pytest/loss_functions/test_loss_functions.py
>      def inference_batch_result_train(self) -> InferenceResultBatch:
done

2022-07-05 22:18 UTC, zengxyu commented on pytest/loss_functions/test_loss_functions.py
>      def inference_batch_result_test(self) -> InferenceResultBatch:
done

2022-07-05 22:47 UTC, zengxyu commented on pytest/loss_functions/test_loss_functions.py
>          assert True
done

2022-07-05 22:58 UTC, zengxyu commented on pytest/loss_functions/test_loss_functions.py
> +        assert True
done

2022-07-05 22:59 UTC, zengxyu commented on pytest/loss_functions/test_multi_loss.py
> +# todo waiting the implementaion of MultiLoss.warm_up() and MultiLoss.finish_warmup()
already deleted the files

2022-07-06 12:05 UTC, le1nux commented
Awesome. Looks good to me! :-)

2022-07-06 12:06 UTC, merged