Br78 test validate
mlgym/mlgym pull request #78
Opened 2022-07-18 21:47 UTC by zengxyu

2022-07-19 14:51 UTC, le1nux requested changes
Looks good so far. Left a few comments. :)

2022-07-19 14:51 UTC, le1nux commented on pytest/validation/test_cross_valildation.py
> +    # # def test_run(self):
commented lines can be deleted

2022-07-20 09:52 UTC, zengxyu commented on src/ml_gym/util/grid_search.py
> +# if __name__ == "__main__":
done

2022-07-20 09:53 UTC, zengxyu commented on pytest/util/test_grid_search.py
> +        print(GridSearch._is_config_equal(c, c))
done

2022-07-20 09:54 UTC, zengxyu commented on pytest/validation/mocked_blueprint.py
> +from typing import Dict, List, Any
nice idea!

2022-07-20 10:03 UTC, zengxyu commented on pytest/validation/test_cross_valildation.py
> +        folder_indices = np.concatenate(indices, axis=0)
I'm not sure if I understand you correctly~ For 5-fold cross-validation, it was split into 5 folds and there is no stratification in each split. I found I wrote the wrong comments here. The indices in each split are shuffled, but I can check the length of each split. :)

2022-07-20 10:03 UTC, zengxyu commented on pytest/validation/test_cross_valildation.py
> +    # # def test_run(self):
done

2022-07-20 12:21 UTC, le1nux approved these changes
LGTM :)

2022-07-20 12:21 UTC, merged